services:
  platonus_bot:
    build: .
    depends_on:
      - db-service 
    container_name: platonus_bot
    # Бот будет автоматически перезапускаться при сбоях или рестарте сервера
    restart: unless-stopped
    
    # Подключаем файл с токеном Telegram и ключом шифрования
    env_file:
      - .env
    user: "1000:1000"
    volumes:
      - .:/app
      
    # В облаке мы просто запускаем главный файл
    command: python main.py
     
  db-service:
   image: postgres:15-alpine
   restart: unless-stopped
   stop_grace_period: 30s # Дать базе данных сохраниться до выкючении
   environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
   ports:
      - "127.0.0.1:5432:5432"
   volumes:
      - pg_data:/var/lib/postgresql/data
volumes:
  pg_data: